### ISSUE TITLE
Docs to use FQCN?

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#29] opened 2020-02-28 18:28 UTC
We need to confirm, though the thought is that we should update documentation to use FQCN.

Module & plugin docs
Examples repos
Training materials

**Comment by samccann** [comment] 2020-03-02 16:04
This should also likely apply to the examples used within the .rst docs. I plan on starting that for the networking stuff, unless I hear otherwise.

**Comment by gundalow** [comment] 2020-03-13 14:27
Modules added only in collection (ie never in devel) MUST have FQCN in `EXAMPLES`

**Comment by geerlingguy** [comment] 2020-04-14 18:30
Closing as duplicate of #40

**Closed by geerlingguy** 2020-04-14 18:30 UTC
