### ISSUE TITLE
[2d] Galaxy build ignore file - tests/output? Others from gitignore

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/overview#53] opened 2020-04-28 15:56 UTC
`ansible-galaxy collection build` has support for an ignore list to prevent files ending up in the built tarball.

Although ideally Collection builds should be happening in a sandbox (CI) their is still the chance that they may include incorrect files.

Also people do build and publish collections locally, where their checkouts maybe dirty.

## Posisble entries
* tests/ (check ansible-base's `.gitignore`
* ignore `.gitignore`

## Once agreed
* update collections under https://github.com/ansible-collections/
* Raise PR to update the default ignore file in https://github.com/ansible/ansible/tree/devel/lib/ansible/galaxy/data/default

**Comment by felixfontein** [comment] 2020-05-01 16:59
I also added the collection build artifacts to build_ignore for a test collection after almost including one into the next version:
```
build_ignore:
  - '<namespace>-<name>-*.tar.gz'
  - .gitignore
```

**Comment by gundalow** [comment] 2020-05-01 20:11
I wonder if `ansible-galaxy collection,role init` should add a default gitignore https://github.com/ansible/ansible/tree/devel/lib/ansible/galaxy/data/default

**Comment by ericsysmin** [comment] 2020-05-07 15:39
A default .gitignore to prevent uploading collection build tar.gz would be nice. I can see a lot of people not deleting those when they do git push after local builds

**Comment by felixfontein** [comment] 2020-05-07 15:42
@ericsysmin is it caused by missing entries in `.gitignore`, or in `build_ignore`, or both?

**Comment by ericsysmin** [comment] 2020-05-07 15:44
.gitignore would prevent people from uploading the .tar.gz to github repeatedly, build already ignores it

*.pyc would be uploaded if not in .gitignore, and not sure if the build already excludes pyc, but you do get those in git if they aren't in your .gitignore, and are created when testing python scripts, or running molecule tests

**Comment by adn1107** [comment] 2021-10-20 21:43
Thanks all. Upgrading to latest Ansible solved the problem.

**Comment by Andersson007** [comment] 2024-05-24 05:59
The repo is getting archived, closing, thanks everyone!

**Closed by Andersson007** 2024-05-24 05:59 UTC
Labels: help wanted
